# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WZAuditory' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WZAuditory
  pod 'SnapKit', '~> 4.0.0'
  pod 'Alamofire'

  target 'WZAuditoryTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WZAuditoryUITests' do
    inherit! :search_paths
    # Pods for testing
  end


end
